app = "blueprint-pm"

[build]
  dockerfile = "Dockerfile"

[[services]]
  protocol = "tcp"
  internal_port = 3000

  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"

[mounts]
  source = "blueprint_data"
  destination = "/data"
  initial_size = "1gb"
