"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import type { Project } from "@/lib/types";

function generateMarkdown(project: Project): string {
  let md = `# ${project.name}\n\n`;
  md += `> ${project.idea}\n\n`;
  md += `---\n\n`;

  if (project.research) {
    md += `## Market Research\n\n`;
    md += `| Metric | Value |\n|--------|-------|\n`;
    md += `| TAM | ${project.research.tam} |\n`;
    md += `| SAM | ${project.research.sam} |\n`;
    md += `| SOM | ${project.research.som} |\n`;
    md += `| Viability | ${project.research.viabilityScore}/100 |\n\n`;
    md += `### Summary\n${project.research.summary}\n\n`;

    if (project.research.competitors.length > 0) {
      md += `### Competitors\n\n`;
      md += `| Company | Strength | Weakness | Differentiation |\n|---------|----------|----------|----------------|\n`;
      project.research.competitors.forEach((c) => {
        md += `| ${c.name} | ${c.strength} | ${c.weakness} | ${c.differentiation} |\n`;
      });
      md += `\n`;
    }
  }

  if (project.stories && project.stories.length > 0) {
    md += `## User Stories\n\n`;
    project.stories.forEach((s) => {
      md += `### ${s.id} — ${s.epic} \[${s.priority}\] \[${s.moscow}\]\n`;
      md += `**${s.story}**\n\n`;
      s.acceptanceCriteria.forEach((ac) => {
        md += `- [ ] ${ac}\n`;
      });
      md += `\n`;
    });
  }

  if (project.wireframes && project.wireframes.length > 0) {
    md += `## Wireframes\n\n`;
    project.wireframes.forEach((wf) => {
      md += `### ${wf.title}\n`;
      md += `${wf.description}\n\n`;
    });
  }

  if (project.prd) {
    md += `## PRD\n\n`;
    md += `### Problem Statement\n${project.prd.problemStatement}\n\n`;
    if (project.prd.goals.length > 0) {
      md += `### Goals\n\n| Goal | Metric | Target |\n|------|--------|--------|\n`;
      project.prd.goals.forEach((g) => {
        md += `| ${g.goal} | ${g.metric} | ${g.target} |\n`;
      });
      md += `\n`;
    }
    if (project.prd.risks.length > 0) {
      md += `### Risks\n\n| Risk | Likelihood | Impact | Mitigation |\n|------|------------|--------|------------|\n`;
      project.prd.risks.forEach((r) => {
        md += `| ${r.risk} | ${r.likelihood} | ${r.impact} | ${r.mitigation} |\n`;
      });
      md += `\n`;
    }
  }

  if (project.roadmap && project.roadmap.length > 0) {
    md += `## Roadmap\n\n`;
    project.roadmap.forEach((phase) => {
      md += `### ${phase.phase} — ${phase.timeline}\n\n`;
      phase.deliverables.forEach((d) => {
        md += `- ${d}\n`;
      });
      md += `\n`;
    });
  }

  md += `\n---\n*Generated by [Blueprint](https://github.com/ArafathUIU/Blueprint)*\n`;
  return md;
}

export function ExportButtons({ project }: { project: Project }) {
  const [copied, setCopied] = useState(false);

  function handleCopyMarkdown() {
    const md = generateMarkdown(project);
    navigator.clipboard.writeText(md).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  function handleDownloadMarkdown() {
    const md = generateMarkdown(project);
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${project.name.replace(/\s+/g, "-").toLowerCase()}-blueprint.md`;
    a.click();
    URL.revokeObjectURL(url);
  }

  function handlePrint() {
    window.print();
  }

  return (
    <div className="flex flex-wrap gap-2">
      <button
        onClick={handleCopyMarkdown}
        className="inline-flex h-9 items-center gap-2 rounded-lg border border-white/10 bg-white/[0.04] px-4 text-xs font-medium text-white/70 transition-all hover:border-white/20 hover:bg-white/[0.08] hover:text-white"
      >
        <svg className="h-3.5 w-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="9" y="9" width="13" height="13" rx="2"/><path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1"/></svg>
        {copied ? "Copied!" : "Copy Markdown"}
      </button>
      <button
        onClick={handleDownloadMarkdown}
        className="inline-flex h-9 items-center gap-2 rounded-lg bg-red-600 px-4 text-xs font-medium text-white transition-all hover:bg-red-500 hover:shadow-lg hover:shadow-red-500/20"
      >
        <svg className="h-3.5 w-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
        Download .md
      </button>
      <button
        onClick={handlePrint}
        className="inline-flex h-9 items-center gap-2 rounded-lg border border-white/10 bg-white/[0.04] px-4 text-xs font-medium text-white/70 transition-all hover:border-white/20 hover:bg-white/[0.08] hover:text-white"
      >
        <svg className="h-3.5 w-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><polyline points="6 9 6 2 18 2 18 9"/><path d="M6 12H4a2 2 0 00-2 2v4a2 2 0 002 2h16a2 2 0 002-2v-4a2 2 0 00-2-2h-2"/><rect x="6" y="14" width="12" height="8"/></svg>
        Print / Save PDF
      </button>
    </div>
  );
}
